if(NOT DEFINED FREETYPE_SOURCE_DIR)
    message(FATAL_ERROR "FREETYPE_SOURCE_DIR must be provided")
endif()

set(FREETYPE_IOS_CMAKE "${FREETYPE_SOURCE_DIR}/builds/cmake/iOS.cmake")
file(READ "${FREETYPE_IOS_CMAKE}" freetype_ios_cmake)

if(NOT freetype_ios_cmake MATCHES "execute_process\\(COMMAND uname")
    string(FIND "${freetype_ios_cmake}" "exec_program(uname ARGS -r OUTPUT_VARIABLE CMAKE_HOST_SYSTEM_VERSION)" uname_offset)
    if(uname_offset EQUAL -1)
        message(FATAL_ERROR "FreeType iOS patch precondition failed: uname invocation not found")
    endif()
    string(REPLACE "exec_program(uname ARGS -r OUTPUT_VARIABLE CMAKE_HOST_SYSTEM_VERSION)" "execute_process(COMMAND uname -r OUTPUT_VARIABLE CMAKE_HOST_SYSTEM_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)" freetype_ios_cmake "${freetype_ios_cmake}")
endif()

if(NOT freetype_ios_cmake MATCHES "SIMULATOR64")
    string(FIND "${freetype_ios_cmake}" "elseif (\${IOS_PLATFORM} STREQUAL \"SIMULATOR\")" simulator_offset)
    if(simulator_offset EQUAL -1)
        message(FATAL_ERROR "FreeType iOS patch precondition failed: simulator branch not found")
    endif()
    string(REPLACE "elseif (\${IOS_PLATFORM} STREQUAL \"SIMULATOR\")" "elseif (\${IOS_PLATFORM} STREQUAL \"SIMULATOR\" OR \${IOS_PLATFORM} STREQUAL \"SIMULATOR64\")" freetype_ios_cmake "${freetype_ios_cmake}")
endif()

if(NOT freetype_ios_cmake MATCHES "set\\(IOS_ARCH arm64\\)")
    string(FIND "${freetype_ios_cmake}" "if (\${IOS_PLATFORM} STREQUAL \"OS\")\n  set(IOS_ARCH \$(ARCHS_STANDARD_32_64_BIT))\nelse (\${IOS_PLATFORM} STREQUAL \"OS\")" arch_offset)
    if(arch_offset EQUAL -1)
        message(FATAL_ERROR "FreeType iOS patch precondition failed: architecture branch not found")
    endif()
    string(REPLACE "if (\${IOS_PLATFORM} STREQUAL \"OS\")\n  set(IOS_ARCH \$(ARCHS_STANDARD_32_64_BIT))\nelse (\${IOS_PLATFORM} STREQUAL \"OS\")" "if (\${IOS_PLATFORM} STREQUAL \"OS\")\n  set(IOS_ARCH \$(ARCHS_STANDARD_32_64_BIT))\nelseif (\${IOS_PLATFORM} STREQUAL \"SIMULATOR64\")\n  set(IOS_ARCH arm64)\nelse (\${IOS_PLATFORM} STREQUAL \"OS\")" freetype_ios_cmake "${freetype_ios_cmake}")
endif()

file(WRITE "${FREETYPE_IOS_CMAKE}" "${freetype_ios_cmake}")
file(READ "${FREETYPE_IOS_CMAKE}" patched_freetype_ios_cmake)
if(NOT patched_freetype_ios_cmake MATCHES "execute_process\\(COMMAND uname" OR NOT patched_freetype_ios_cmake MATCHES "SIMULATOR64" OR NOT patched_freetype_ios_cmake MATCHES "set\\(IOS_ARCH arm64\\)")
    message(FATAL_ERROR "FreeType iOS patch verification failed")
endif()
